#!/bin/bash
#
# tools/update-dmg-url.sh — Maintainer tool to refresh pinned DMG metadata
#
# Queries Anthropic's API (via rnet) for the latest DMG URL and version,
# then updates dmg-latest.env in the repo root. Commit the result.
#
# This tool is for MAINTAINERS ONLY. End users never need rnet.
#
# Usage:
#   tools/update-dmg-url.sh           # Update dmg-latest.env
#   tools/update-dmg-url.sh --check   # Check if update is available (no write)
#
# Requirements: python3, pip

set -euo pipefail

RNET_PIP_SPEC="rnet>=3.0.0rc14"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$REPO_ROOT/dmg-latest.env"

FETCH_SCRIPT=""
for candidate in "$REPO_ROOT/fetch-dmg.py" "$SCRIPT_DIR/fetch-dmg.py"; do
    if [[ -f "$candidate" ]]; then
        FETCH_SCRIPT="$candidate"
        break
    fi
done
[[ -n "$FETCH_SCRIPT" ]] || { echo "ERROR: fetch-dmg.py not found"; exit 1; }

CHECK_ONLY=false
[[ "${1:-}" == "--check" ]] && CHECK_ONLY=true

# Set up temporary venv
VENV_DIR=$(mktemp -d)
cleanup() { rm -rf "$VENV_DIR" 2>/dev/null || true; }
trap cleanup EXIT INT TERM

echo "Installing rnet..."
python3 -m venv "$VENV_DIR"
"$VENV_DIR/bin/pip" install --quiet --pre "$RNET_PIP_SPEC"

echo "Querying API..."
OUTPUT=$("$VENV_DIR/bin/python3" "$FETCH_SCRIPT" 2>/dev/null) || {
    echo "ERROR: Failed to query API"; exit 1;
}

# Parse: "VERSION URL [SHA256]"
DMG_VERSION=$(echo "$OUTPUT" | awk '{print $1}')
DMG_URL=$(echo "$OUTPUT" | awk '{print $2}')
DMG_SHA256=$(echo "$OUTPUT" | awk '{print $3}')  # may be empty

echo "Latest version: $DMG_VERSION"
echo "CDN URL: $DMG_URL"
[[ -n "$DMG_SHA256" ]] && echo "SHA-256: $DMG_SHA256" || echo "SHA-256: (not provided by API)"

if $CHECK_ONLY; then
    if [[ -f "$ENV_FILE" ]]; then
        CURRENT_VERSION=$(grep '^DMG_VERSION=' "$ENV_FILE" 2>/dev/null | cut -d= -f2 | tr -d '"')
        if [[ "$CURRENT_VERSION" == "$DMG_VERSION" ]]; then
            echo "Already up to date."
        else
            echo "Update available: $CURRENT_VERSION → $DMG_VERSION"
        fi
    else
        echo "No dmg-latest.env found — run without --check to create it."
    fi
    exit 0
fi

# If maintainer wants to pin the SHA-256, download and compute it
if [[ -z "$DMG_SHA256" ]]; then
    echo ""
    read -rp "API didn't provide SHA-256. Download DMG to compute it? [y/N] " answer
    if [[ "$answer" =~ ^[Yy] ]]; then
        TMP_DMG=$(mktemp)
        echo "Downloading DMG to compute SHA-256..."
        if curl -fSL --progress-bar -o "$TMP_DMG" "$DMG_URL"; then
            DMG_SHA256=$(sha256sum "$TMP_DMG" | awk '{print $1}')
            echo "Computed SHA-256: $DMG_SHA256"
            rm -f "$TMP_DMG"
        else
            echo "Download failed — skipping SHA-256"
            rm -f "$TMP_DMG"
        fi
    fi
fi

# Write env file
cat > "$ENV_FILE" << EOF
# Auto-generated by tools/update-dmg-url.sh — do not edit manually
# Updated: $(date -u '+%Y-%m-%dT%H:%M:%SZ')
DMG_VERSION="$DMG_VERSION"
DMG_URL="$DMG_URL"
DMG_SHA256="${DMG_SHA256:-}"
EOF

echo ""
echo "Updated: $ENV_FILE"
echo "Commit this file and tag a release."
